# Generated by Django 5.2.8 on 2025-11-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=20, unique=True, verbose_name='ИНН')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('status', models.CharField(max_length=128, verbose_name='Статус')),
                ('decision_number', models.CharField(blank=True, default='', max_length=128, verbose_name='Номер решения')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='Дата решения')),
                ('registry_record_date', models.DateField(blank=True, null=True, verbose_name='Дата записи в реестре')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Исходные данные')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Аккредитация компании',
                'verbose_name_plural': 'Аккредитации компаний',
                'ordering': ['-checked_at'],
            },
        ),
    ]
